### ISSUE TITLE
Print Button Below the post

### ISSUE THREAD

**Issue by uwefunk** [mnelson4/printmyblog#57] opened 2020-02-20 14:36 UTC
Hi Mike,

very exiting plugin. Just a got a request from a customer to print certain posts from my blog: https://digitales-fuer-einsteiger.de/das-ideale-smartphone-fuer-einsteiger/ 
So I installed your plugin and in generals it shows perfect results. 

The only request I would have is to place the print/PDF button below the post and not above. Is there an option for?

Regards, Uwe

**Comment by mnelson4** [comment] 2020-02-20 18:00
Hi @uwefunk, sorry that isn’t an option yet (to be honest, I’ve been waiting to hear if anybody wanted it!)
Adding it properly may take a while (given other feature requests in the queue) but would a code snippet work for you?

**Comment by uwefunk** [comment] 2020-02-20 19:08
Hi @mnelson4 yep, a code snippet (to be placed in the functions.php ?) would fit.

**Comment by mnelson4** [comment] 2020-02-21 01:02
Ok I’ll probably need to add a filter or something too, but I’ll try to make that available ASAP. Would you mind testing it before I release a new version of the plugin?

**Comment by uwefunk** [comment] 2020-02-21 08:11
Yes, I can test it accordingly. I have a staging environment available.

**Comment by mnelson4** [comment] 2020-02-22 07:02
Hi @uwefunk I've created a branch https://github.com/mnelson4/printmyblog/tree/FET/filter-button-placement, you can download a zip of it here: https://github.com/mnelson4/printmyblog/archive/FET/filter-button-placement.zip
With that branch activated on the site, add this code to `functions.php`: 

```
add_filter('\PrintMyBlog\controllers\PmbFrontend->addPrintButton $add_to_top', '__return_false');
```
Then the print buttons should appear in the footer.

**Comment by uwefunk** [comment] 2020-02-24 16:18
Hi @mnelson4 Excellent. In General it works. The button is below the post. But .... Your plugin somehow breaks this post, means there areas where a Foto gallery should appear but it's not showing. Enclosed two screenshots for explanation. In case you would investigate the issue I could provide credentials for this staging environment. 
<img width="1241" alt="Bildschirmfoto 2020-02-24 um 17 15 36" src="https://user-images.githubusercontent.com/38373905/75169892-96976000-5729-11ea-9742-f6149e3ec53f.png">
<img width="1278" alt="Bildschirmfoto 2020-02-24 um 17 15 46" src="https://user-images.githubusercontent.com/38373905/75169905-9a2ae700-5729-11ea-83e7-1241eaa58a93.png">

**Comment by mnelson4** [comment] 2020-02-24 16:36
Hi @uwefunk hmmm that's strange. What plugin are you using to add the photo gallery? Can you confirm that turning off the print buttons, or removing the filter, leaves the photo gallery intact?

**Comment by uwefunk** [comment] 2020-02-24 16:40
Hi @mnelson4 Yes, if I deactivate the plugin all works fine - just tested. For the gallery I use the elements of my theme: AVADA.

**Comment by mnelson4** [comment] 2020-02-24 19:24
Hmmm ok thanks. Yeah if you could send me the URL of that test site that would be helpful, so I could check for any Javascript errors coming from my plugin while viewing the frontend. But beyond that I won't be able to provide free support for integration with paid themes/plugins.
Also, FYI the print buttons are just hyperlinks to special URLs for printing, so you can actually place a hyperlink to them from anywhere you want on the page.

**Comment by mnelson4** [comment] 2020-02-24 20:21
> But beyond that I won't be able to provide free support for integration with paid themes/plugins.

Nevermind- I checked with my "mastermind group" and it's best to figure out if this is a generic problem or one specific to your setup. Regardless, I think just getting the URL of your staging site would be the best first step (and if I can't figure it out from that, then try to reproduce it with Avada etc.)

**Comment by uwefunk** [comment] 2020-02-25 08:01
Hi @mnelson4 thank you so much for your support in this matter. I really appreciate it. Here comes the URL to the "broken" post: https://save.connect45plus.de/hotspot-einrichten/

**Comment by mnelson4** [comment] 2020-02-26 05:37
Hi @uwefunk I got to the bottom of the issue: Print My Blog was using a different, incompatible version of a jQuery library (debounce) than what your carousel/photo gallery plugin was using.
If you re-download the test version (https://github.com/mnelson4/printmyblog/archive/FET/filter-button-placement.zip) it should work, as it's now using the same version of jQuery debounce.

**Comment by uwefunk** [comment] 2020-02-26 08:12
Hi @mnelson4 It's getting perfect. Now the appearance oft the blog post ist fine, but ... If I press the print button the print preview shows the same issue as the blog post before. See attached screenshots 
<img width="1083" alt="Bildschirmfoto 2020-02-26 um 09 08 26" src="https://user-images.githubusercontent.com/38373905/75324750-eab05a80-5877-11ea-81f2-e46b2d232b69.png">

The Url for the print issue: https://save.connect45plus.de/?post-type=post&include-private-posts=1&show_site_title=1&show_site_tagline=1&show_site_url=1&show_date_printed=1&show_title=1&show_date=1&show_categories=1&show_featured_image=1&show_content=1&post-page-break=on&columns=1&font-size=normal&image-size=medium&links=parens&rendering-wait=10&print-my-blog=1&format=print&pmb-post=14450

Additional question: is there an option to eliminate the links in the print output also in the version for visitors?

**Comment by mnelson4** [comment] 2020-02-26 23:37
Hi @uwefunk the photo galleries aren't appearing on the print page because they rely on some Javascript to load, but they aren't aware they should load it on the print page. 
Even if I did get it to solve, I don't think those sliding galleries would work on a printed page, because paper obviously isn't dynamic...
I would be inclined to either use a different gallery (that lays them all out on the page, so they'll all be visible when printing... I know Print My Blog works with FooGallery) or use the CSS classes described in these FAQs (see https://wordpress.org/plugins/print-my-blog/#how%20do%20i%20remove%20post%20content%20from%20the%20printout%3F and https://wordpress.org/plugins/print-my-blog/#how%20do%20i%20make%20post%20content%20only%20appear%20in%20the%20printout%3F) to show something different in print (eg a different gallery, no just show nothing at all if the gallery images aren't essential in print.)
What do you think of that?

> is there an option to eliminate the links in the print output also in the version for visitors?

So far there's no customization options for those (although someone else did just ask last week, so it's going up on my priorities). I could add a filter for a quickfix there too. Out of curiosity, are you wanting to remove the hyperlinks, or just the URL in parenthesis?

**Comment by uwefunk** [comment] 2020-02-27 08:49
Hi @mnelson4 Ok. Understood. I will a have a look for an alternative regarding the gallery issue.

Concerning the URL - I just want to remove the URL in parenthesis. The hyperlink should remain especially if the document is outputted as a PDF.

**Comment by uwefunk** [comment] 2020-02-27 16:53
Hi @mnelson4 I made another try. I replaced all the before use image carousel elements and replaced it with an image gallery (from AVAD) element where all pictures are shown at once. See the URL: https://save.connect45plus.de/hotspot-einrichten/ But if I try to print they disappear completely ...

**Comment by mnelson4** [comment] 2020-02-28 05:39
Hey @uwefunk, I looked into it and it looks like that "Fusion gallery" (which, confusingly, I don't think is the same as https://wordpress.org/plugins/fusion-extension-gallery/) was waiting for some Javascript to reveal it, which it wasn't.
I tweaked Print My Blog to try to override the CSS to make the images appear. If you re-download https://github.com/mnelson4/printmyblog/archive/FET/filter-button-placement.zip hopefully you'll see the image gallery this time.

**Comment by uwefunk** [comment] 2020-02-28 16:58
Hi @mnelson4 Now it (almost) works. The images are visible in the print-output-preview, but not in the output itself. Also all the colors of buttons etc. (which are shown in the preview) are not on the printout. 

Regarding the URL's - not to show in parenthesis - is there a solution for? Especially to call the print plugin with a certain parameter?

This would be anyway the preferred solution, that I could place customized buttons at the end of selected post, which would print/pdf the current post. Is this an option? That would mean, that not the post-id is part of the url but somehow a generic URL which would select the current post. Is this thinkable or completely nonsens? 

I drafted an example how I could image such a button. You see it at the end of the post: https://save.connect45plus.de/hotspot-einrichten/

**Comment by mnelson4** [comment] 2020-02-29 04:37
> Also all the colors of buttons etc. (which are shown in the preview) are not on the printout.

I think I'm seeing the images in Firefox' print preview, when generating a PDF using "Print to PDF" Firefox extension, and in Google Chrome's print preview/generating a PDF. See https://drive.google.com/file/d/17FzOjAe0lwAe3TZBigpVt1KSSEvLTjAq/view
What are you seeing?

> Regarding the URL's - not to show in parenthesis - is there a solution for? Especially to call the print plugin with a certain parameter?

Yes I added a filter in the latest release, so you can override the defaults. This code snippet does that:

```
function no_link_in_parens($query_args, $post){
    $query_args['links'] = 'remove';
    return $query_args;
}
add_filter('\PrintMyBlog\controllers\PmbFrontend->addPrintButton $base_args', 'no_link_in_parens', 10, 2);
```

But as you probably noticed, the default for PDFs is to *not* add the links in parenthesis anyway (although you should be aware Firefox and Safari generate PDFs without hyperlinks.)

>  I could place customized buttons at the end of selected post, which would print/pdf the current post. Is this an option?

Yeah I've thought about that but you're the first to actually request it. I thought about adding a Gutenberg block or a shortcode to add it. You're right that it's mostly just a regular URL you're linking to, but you'll need to dynamically set the post's ID in the querystring.

**Comment by uwefunk** [comment] 2020-03-03 10:35
> I think I'm seeing the images in Firefox' print preview, when generating a PDF using "Print to PDF" Firefox extension, and in Google Chrome's print preview/generating a PDF. See https://drive.google.com/file/d/17FzOjAe0lwAe3TZBigpVt1KSSEvLTjAq/view
What are you seeing?

I see different content in the preview and in the final printout. Enclosed a screenshot for preview and the pdf-scan of the real print. 
<img width="1017" alt="Bildschirmfoto 2020-03-03 um 11 21 09" src="https://user-images.githubusercontent.com/38373905/75766990-4f6d2880-5d42-11ea-8534-01ef71e88263.png">
[Printout-Post-Hotspot.pdf](https://github.com/mnelson4/printmyblog/files/4280741/Printout-Post-Hotspot.pdf)

> Yes I added a filter in the latest release, so you can override the defaults. This code snippet does that:

This is ok. Added it the functions.php and it seems to work

> Yeah I've thought about that but you're the first to actually request it. I thought about adding a Gutenberg block or a shortcode to add it. You're right that it's mostly just a regular URL you're linking to, but you'll need to dynamically set the post's ID in the querystring.

This ist the current loink which is behind the button: https://save.connect45plus.de/?post-type=post&include-private-posts=1&show_site_title=1&show_site_tagline=1&show_site_url=1&show_date_printed=1&show_title=1&show_date=1&show_categories=1&show_featured_image=1&show_content=1&post-page-break=on&columns=1&font-size=normal&image-size=medium&links=parens&rendering-wait=10&print-my-blog=1&format=print&pmb-post=14450 

How can I switch off the URL's in this link? And is there an option to identify the "current post" somehow instead of the post-id 14450 in this case?

**Comment by mnelson4** [comment] 2020-03-04 17:05
> I see different content in the preview and in the final printout. Enclosed a screenshot for preview and the pdf-scan of the real print.

Thanks for sharing the screenshot and file. I'm pretty sure it's because one of your popups is appearing in front of the images, so only the bottom half of them appear. May I ask what you're using the popup at the top and the one at the bottom-right?

If you add this CSS to your theme it should remove those popups in the printouts, but leave them during normal visits.

```
.pmb-print-page .cp-slidein-popup-container{
    display:none;
}
.pmb-print-page .grecaptcha-badge{
display:none !important;
}
.pmb-print-page .cp-info-bar-container{
display:none !important;
}
```
That should fix the issue with the image being cut off.

> How can I switch off the URL's in this link?

Changes `links=parens` to `links=remove` (that's what [the last code snippet](https://github.com/mnelson4/printmyblog/issues/57#issuecomment-592867473) I gave you did.)

> And is there an option to identify the "current post" somehow instead of the post-id 14450 in this case?

If you're generating the link in PHP code, you can use `get_the_ID()` (see https://developer.wordpress.org/reference/functions/get_the_id/). If you're generating the link in a post's body, [this code snippet shows how to use a shortcode to get the current post's ID](https://wordpress.stackexchange.com/a/248907/52760).

**Comment by uwefunk** [comment] 2020-03-05 15:11
@mnelson4 Again many thanks for your great support.
I'm now a few steps further.
I brought the plugin and all the setup from the staging in the production environment.
I will use the print option for the moment only via customized button, where I set the post-id individually.

The first example you find here: https://digitales-fuer-einsteiger.de/smartphone-test-redmi-note-8-by-xiaomi/ You see the button on the bottom right.

It works almost perfect - but - the images (standard images, no gallery, no carousel) do not appear neither in the preview nor in the printout.

This is the link, which is behind the button:

https://digitales-fuer-einsteiger.de/?post-type=post&include-private-posts=1&show_site_title=1&show_site_tagline=1&show_site_url=1&show_date_printed=1&show_title=1&show_date=1&show_categories=0&show_featured_image=0&show_content=1&post-page-break=on&columns=1&font-size=normal&image-size=medium&links=remove&rendering-wait=10&print-my-blog=1&format=print&pmb-post=15437

**Comment by mnelson4** [comment] 2020-03-09 18:50
Ok great, ya that's coming along... It seems a lazy loading plugin is hiding the images (and it's waiting for some Javascript to trigger loading them, but that Javascript obviously hasn't gotten enqueued on the print page).
Do you know how you're lazy loading your images? (ie, what plugin?)

**Comment by uwefunk** [comment] 2020-03-10 07:45
Hi @mnelson4 the lazy load was an option in the theme AVADA - section performance. I switched it off and the next steps is done, the images are seen in the print preview... 
But ..... now the Button Drucke (print) is visible but can't be used/pressed, See attached screenshot
<img width="1051" alt="Bildschirmfoto 2020-03-10 um 08 41 17" src="https://user-images.githubusercontent.com/38373905/76290294-454faa80-62ab-11ea-81a1-0c98fc11d47a.png">

The link behind the button: https://digitales-fuer-einsteiger.de/?post-type=post&include-private-posts=1&show_site_title=1&show_site_tagline=1&show_site_url=1&show_date_printed=1&show_title=1&show_date=1&show_categories=0&show_featured_image=0&show_content=1&post-page-break=on&columns=1&font-size=normal&image-size=medium&links=remove&rendering-wait=10&print-my-blog=1&format=print&pmb-post=15437

P.S. I've also updated your plugin because it was said that a new version (2.3.3) is available

**Comment by mnelson4** [comment] 2020-03-10 19:38
Hi @uwefunk, it would be good for me to get lazy loaded images for Avada, but I don’t have a copy. If you’d like to send me a copy of Avada through my contact page that would be helpful: https://cmljnelson.blog/contact-me/

It’s weird the button is floating to the side, but it’s working for me from my iPhone using Safari. I think sometimes browsers can disable it if you press it too much (they start to think there’s a bug). Does the button still not work if you clear your browser’s history? Or use a different browser?
I think I’ll add some text telling folks they can also just use their browser to print (in case the print button gets disabled, like I think is happening to you.)

**Comment by uwefunk** [comment] 2020-03-11 12:57
Hi @mnelson4 it's somehow strange. If i use just the print command (Firefox, Mac) I get the error message as follows:

<img width="1235" alt="Bildschirmfoto 2020-03-11 um 13 47 39" src="https://user-images.githubusercontent.com/38373905/76418758-7b6e5680-639f-11ea-84ec-17991b25fb83.png">
(Document can't be printed because it's still loading).

Also in Safari Mac the print button (from your plugin) is deactivated. See the screenshot:
<img width="1126" alt="Bildschirmfoto 2020-03-11 um 13 54 13" src="https://user-images.githubusercontent.com/38373905/76419021-f2a3ea80-639f-11ea-98e1-6961a8bc3493.png"> In this case I can use the standard print function from safari, this works.

What do you mean with "a copy of AVADA"?

**Comment by mnelson4** [comment] 2020-03-11 23:11
Regarding the warning that you're getting, I'm sorry I'm not reproducing it in Firefox or Chrome on Windows, nor Safari or Chrome on Mac. It looks like it might be coming from your printer. This article might be helpful: https://answers.microsoft.com/de-de/msoffice/forum/msoffice_word-mso_win10-mso_2016/word-dokumente-werden-nicht-mehr-gedruckt/4dda585a-f3b2-4e35-98df-bc878165b020?auth=1 . It seems if you basically restart everything (your computer, the printer, etc) the error may go away.

> Also in Safari Mac the print button (from your plugin) is deactivated.

I actually don't see the button being deactivated in your screenshot. I can click it and it triggers printing in every browser I've tried. BUT I see that the cursor doesn't change to a hand like you'd expect. That's because of some CSS coming from https://digitales-fuer-einsteiger.de/wp-content/uploads/fusion-styles/5e7781d36328bbdb3e3978ac401c4252.min.css?ver=2.2.1 . I'm not sure if that CSS is from your theme or a plugin...
Either way, I bet you're not the only one who's had that. I'll add some CSS to Print My Blog to override that, and force the button to be centered too.

Please try using https://github.com/mnelson4/printmyblog/archive/BUG/avada-input.zip ; it should make the button appear clickable, center it; and add some text informing the user they should use their browser to print (in case the browser disables the button like might be happening to you.)

> What do you mean with "a copy of AVADA"?

In order to debug the issue with Avada's lazy loading, it would help if I could use the theme on one of my test's sites. I'd rather not buy it as I won't be using in on a site, so I was asking if you could use my contact form to send me an email. I'll reply so you can see what my email is, and then you can put the theme in a zip file and email it to me. Any software derived from WordPress (like themes) are GPL so it's ok to share.

**Comment by uwefunk** [comment] 2020-03-12 13:25
Hi @mnelson4 I think, I'm now in a status, where I will use the plugin in my production environment . I again switched to the "print each post" setup and not an individual link/button on selected posts but customized it color wise via css. See the outcome here:
<img width="916" alt="Bildschirmfoto 2020-03-12 um 14 17 06" src="https://user-images.githubusercontent.com/38373905/76525697-9d81da80-646c-11ea-91b3-56741ae1961d.png">

So, I would like to talk you very much for your endless support. It really helped. You will also be mentioned (if it is of for you) in my newsletter published next weeks Thursday in this sense.

I'm also interested to be one of the "founding members" of the PRO version. I've subscribed to you mailing list accordingly.

And last but not least, I used your contact form to prepare the AVADA transfer for your tests.

Regards, Uwe

**Comment by uwefunk** [comment] 2020-03-12 14:28
Hi @mnelson4 One final question. I tried to not display the print button on selected posts. I used this css:

.page-id-15437 .wp-block-button {
    display: none !important;
}

But it has ho effect. If I use it without a page-id, it works and all buttons on all posts disappear.

**Comment by mnelson4** [comment] 2020-03-12 18:41
Great to hear it's pretty well ready for production!

I would use this CSS instead to hide the button on specific posts:

```
.post-15437 .pmb-print-this-page{
    display:none;
}
```
(notice it uses `.post-` instead of `.post-id`; also I thought you might not want to hide all button blocks, so used `.pmb-print-this-page` instead of `.wp-block-button.)

Great to hear you're interested in helping to shape the pro version, and ya it would be great to get a mention in your newsletter.

I'm not going to close this issue as the main issue, "Print button below the post" can only be done by using a filter, and I'd like to instead make an option for that.

**Comment by mnelson4** [comment] 2020-03-13 04:10
Oh and FYI it would may want to translate some of the newer strings to German here: https://translate.wordpress.org/locale/de/default/wp-plugins/print-my-blog/ (I admit it's been tough for translators to keep up with all my changes.)

**Comment by uwefunk** [comment] 2020-03-13 15:25
> I would use this CSS instead to hide the button on specific posts:
> 
> ```
> .post-15437 .pmb-print-this-page{
>     display:none;
> }
> ```

Perfect. This works. So I applied it for all posts which are still using the image carousel element and it gives me the time to re-work these post by post.

**Comment by uwefunk** [comment] 2020-03-13 15:40
> Oh and FYI you may want to translate some of the newer strings to German here: https://translate.wordpress.org/locale/de/default/wp-plugins/print-my-blog/ (I admit it's been tough for translators to keep up with all my changes.)

I've started some translation work. Will see whether my suggestions are confirmed and then continue.

**Comment by mnelson4** [comment] 2020-03-14 04:29
Thanks! Ya I know what you mean... I actually translated it all into French at one point, but no one ever confirmed them 😥. What's nice is that German at least was fully translated at one point, so you I think you can just translate the few strings users will read, not the entire thing (I know that can take a long time.)

**Comment by mnelson4** [comment] 2020-10-08 07:36
I added the option to put the buttons below page content a few months ago, so closing this

**Closed by mnelson4** 2020-10-08 07:36 UTC
